services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: default_user # Replace with a strong password
      POSTGRES_USER: default
      POSTGRES_DB: mytodo_db # Database name for your app
    ports:
      - "5432:5432" # Map container port 5432 to host port 5432
    volumes:
      - postgres:/var/lib/postgresql/data # Persist data volume

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: default@gmail.com # Replace with your email (optional)
      PGADMIN_DEFAULT_PASSWORD: default # Replace with a strong password 
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  postgres:
  pgadmin-data:
